# Generated by Django 6.0 on 2025-12-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='about/')),
                ('image2', models.ImageField(upload_to='about/')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sub_heading', models.CharField(max_length=100)),
                ('my_list', models.JSONField(default=list)),
            ],
        ),
    ]
